### ISSUE TITLE
matar eu do coração

### ISSUE THREAD

**Issue by lukinhanw** [joaquinito01/Xtream-Codes-2.2.0-Nulled#1]
Nossa mano quase tive um piripaque achando q era vdd

**Comment by joaquinito01** [comment]
En el 220-fixed será solucionado el problema.
In 220-fixed will be fix the problem.
Gracias.
Thank you.

**Comment by lukinhanw** [comment]
[*] Enter Your ipTV licence: 3d5b0f8e468c332
PHP Warning:  file_get_contents(http://xtream-codes.com/softwares/iptv_panel/iptv_download.php?licence=3d5b0f8e468c332): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
 in Xtream_Codes on line 301

**Comment by xoceunder** [comment]
I have the same problem as lukinhanw

**Comment by edwinn67** [comment]
same problem here
